# Etapa 1 — Coleta e Importação dos Dados (Python / Pandas)

In [ ]:
%pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
%pip install matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.10.9)
Requirement already satisfied: seaborn in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from seaborn) (3.0.2)
Requirement already satisfied: tzdata in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in D:\Users\Aluno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
#Importar o arquivo .csv utilizando pandas

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r'E:\David Curso Analista de Dados\projeto integrador\vendas_varejo_facil.csv', encoding='utf-8-sig')

df

,id_venda,data_venda,id_cliente,nome_cliente,cidade,estado,categoria,produto,quantidade,valor_unitario,desconto,valor_total,forma_pagamento,avaliacao_cliente
0,1,2024-02-22,347,Cliente_0347,Porto Alegre,RS,Eletrônicos,Smartphone,2,1754.83,0.00,3509.67,PIX,5.0
1,2,2024-09-15,309,Cliente_0309,São Paulo,SP,Casa & Decoração,Luminária,2,140.63,0.00,281.26,Cartão de Crédito,2.0
2,3,2024-01-04,389,Cliente_0389,Olinda,PE,Casa & Decoração,Tapete,3,312.87,0.20,750.90,PIX,5.0
3,4,2024-02-17,195,Cliente_0195,Belo Horizonte,MG,Alimentos,Azeite Importado,3,80.56,0.00,241.68,Boleto,3.0
4,5,2024-02-10,283,Cliente_0283,Olinda,PE,Alimentos,Café Premium,1,41.90,0.05,39.81,PIX,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,2024-05-15,390,Cliente_0390,Salvador,BA,Eletrônicos,Smartwatch,1,825.11,0.00,825.11,PIX,4.0
1996,1997,2024-06-27,351,Cliente_0351,Aparecida de Goiânia,GO,Casa & Decoração,Almofada,5,75.30,0.05,357.68,PIX,3.0
1997,1998,2024-09-30,202,Cliente_0202,Curitiba,PR,Alimentos,Granola,2,25.59,0.15,43.50,Boleto,5.0
1998,1999,2024-07-17,331,Cliente_0331,Campinas,SP,Eletrônicos,Notebook,3,3189.94,0.00,9569.81,PIX,3.0
1999,2000,2024-03-24,489,Cliente_0489,Recife,PE,Alimentos,Café Premium,3,43.04,0.20,103.30,PIX,3.0

In [ ]:
#Verificar o shape do DataFrame (linhas e colunas)

df.shape
print("Shape:", df.shape)

Shape: (2000, 14)

In [ ]:
#Visualizar as primeiras e últimas linhas (head(), tail())

df.head

print('Head:', df.head())

Head:    id_venda  data_venda  id_cliente  nome_cliente          cidade estado  \
0         1  2024-02-22         347  Cliente_0347    Porto Alegre     RS
1         2  2024-09-15         309  Cliente_0309       São Paulo     SP
2         3  2024-01-04         389  Cliente_0389          Olinda     PE
3         4  2024-02-17         195  Cliente_0195  Belo Horizonte     MG
4         5  2024-02-10         283  Cliente_0283          Olinda     PE

          categoria           produto  quantidade  valor_unitario  desconto  \
0       Eletrônicos        Smartphone           2         1754.83      0.00
1  Casa & Decoração         Luminária           2          140.63      0.00
2  Casa & Decoração            Tapete           3          312.87      0.20
3         Alimentos  Azeite Importado           3           80.56      0.00
4         Alimentos      Café Premium           1           41.90      0.05

   valor_total    forma_pagamento  avaliacao_cliente
0      3509.67                PIX                5.0
1       281.26  Cartão de Crédito                2.0
2       750.90                PIX                5.0
3       241.68             Boleto                3.0
4        39.81                PIX                4.0

In [ ]:
#Visualizar as primeiras e últimas linhas (head(), tail())

df.tail

print('Tail:', df.tail())

Tail:       id_venda  data_venda  id_cliente  nome_cliente                cidade  \
1995      1996  2024-05-15         390  Cliente_0390              Salvador
1996      1997  2024-06-27         351  Cliente_0351  Aparecida de Goiânia
1997      1998  2024-09-30         202  Cliente_0202              Curitiba
1998      1999  2024-07-17         331  Cliente_0331              Campinas
1999      2000  2024-03-24         489  Cliente_0489                Recife

     estado         categoria       produto  quantidade  valor_unitario  \
1995     BA       Eletrônicos    Smartwatch           1          825.11
1996     GO  Casa & Decoração      Almofada           5           75.30
1997     PR         Alimentos       Granola           2           25.59
1998     SP       Eletrônicos      Notebook           3         3189.94
1999     PE         Alimentos  Café Premium           3           43.04

      desconto  valor_total forma_pagamento  avaliacao_cliente
1995      0.00       825.11             PIX                4.0
1996      0.05       357.68             PIX                3.0
1997      0.15        43.50          Boleto                5.0
1998      0.00      9569.81             PIX                3.0
1999      0.20       103.30             PIX                3.0

In [ ]:
#Verificar os tipos de dados (dtypes)

df.dtypes

print('Data Types:', df.dtypes)

Data Types: id_venda               int64
data_venda               str
id_cliente             int64
nome_cliente             str
cidade                   str
estado                   str
categoria                str
produto                  str
quantidade             int64
valor_unitario       float64
desconto             float64
valor_total          float64
forma_pagamento          str
avaliacao_cliente    float64
dtype: object

In [ ]:
#Conferir se há valores nulos (isnull().sum())

df.isnull().sum()

print('Valores Nulos:', df.isnull().sum())

Valores Nulos: id_venda              0
data_venda            0
id_cliente            0
nome_cliente          0
cidade                0
estado                0
categoria             0
produto               0
quantidade            0
valor_unitario        0
desconto             20
valor_total           0
forma_pagamento       0
avaliacao_cliente    20
dtype: int64

## Etapa 2 — Limpeza e Tratamento dos Dados (Python / Pandas)

In [ ]:
#Tratar valores nulos (substituir ou remover conforme o contexto)

df['desconto'] = df['desconto'].fillna(0)

print('Valores Nulos após tratamento:', df.isnull().sum())

Valores Nulos após tratamento: id_venda              0
data_venda            0
id_cliente            0
nome_cliente          0
cidade                0
estado                0
categoria             0
produto               0
quantidade            0
valor_unitario        0
desconto              0
valor_total           0
forma_pagamento       0
avaliacao_cliente    20
dtype: int64

In [ ]:
#Notas Nulas o ciente pode apenas não ter avaliado

df['avaliacao_cliente'] = pd.to_numeric(df['avaliacao_cliente'], errors='coerce')

nao_avaliados = df['avaliacao_cliente'].isnull().sum()
print(f'Clientes que não avaliaram: {nao_avaliados}')

Clientes que não avaliaram: 20

In [ ]:
#Converter a coluna data_venda para o tipo datetime

df['data_venda'] = pd.to_datetime(df['data_venda'])

df

,id_venda,data_venda,id_cliente,nome_cliente,cidade,estado,categoria,produto,quantidade,valor_unitario,desconto,valor_total,forma_pagamento,avaliacao_cliente
0,1,2024-02-22,347,Cliente_0347,Porto Alegre,RS,Eletrônicos,Smartphone,2,1754.83,0.00,3509.67,PIX,5.0
1,2,2024-09-15,309,Cliente_0309,São Paulo,SP,Casa & Decoração,Luminária,2,140.63,0.00,281.26,Cartão de Crédito,2.0
2,3,2024-01-04,389,Cliente_0389,Olinda,PE,Casa & Decoração,Tapete,3,312.87,0.20,750.90,PIX,5.0
3,4,2024-02-17,195,Cliente_0195,Belo Horizonte,MG,Alimentos,Azeite Importado,3,80.56,0.00,241.68,Boleto,3.0
4,5,2024-02-10,283,Cliente_0283,Olinda,PE,Alimentos,Café Premium,1,41.90,0.05,39.81,PIX,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,2024-05-15,390,Cliente_0390,Salvador,BA,Eletrônicos,Smartwatch,1,825.11,0.00,825.11,PIX,4.0
1996,1997,2024-06-27,351,Cliente_0351,Aparecida de Goiânia,GO,Casa & Decoração,Almofada,5,75.30,0.05,357.68,PIX,3.0
1997,1998,2024-09-30,202,Cliente_0202,Curitiba,PR,Alimentos,Granola,2,25.59,0.15,43.50,Boleto,5.0
1998,1999,2024-07-17,331,Cliente_0331,Campinas,SP,Eletrônicos,Notebook,3,3189.94,0.00,9569.81,PIX,3.0
1999,2000,2024-03-24,489,Cliente_0489,Recife,PE,Alimentos,Café Premium,3,43.04,0.20,103.30,PIX,3.0

In [ ]:
#Extrair novas colunas: mes, ano, trimestre a partir de data_venda

#mês

df['mes'] = df['data_venda'].dt.month_name(locale='pt_BR')

df.head()

,id_venda,data_venda,id_cliente,nome_cliente,cidade,estado,categoria,produto,quantidade,valor_unitario,desconto,valor_total,forma_pagamento,avaliacao_cliente,mes
0,1,2024-02-22,347,Cliente_0347,Porto Alegre,RS,Eletrônicos,Smartphone,2,1754.83,0.00,3509.67,PIX,5.0,Fevereiro
1,2,2024-09-15,309,Cliente_0309,São Paulo,SP,Casa & Decoração,Luminária,2,140.63,0.00,281.26,Cartão de Crédito,2.0,Setembro
2,3,2024-01-04,389,Cliente_0389,Olinda,PE,Casa & Decoração,Tapete,3,312.87,0.20,750.90,PIX,5.0,Janeiro
3,4,2024-02-17,195,Cliente_0195,Belo Horizonte,MG,Alimentos,Azeite Importado,3,80.56,0.00,241.68,Boleto,3.0,Fevereiro
4,5,2024-02-10,283,Cliente_0283,Olinda,PE,Alimentos,Café Premium,1,41.90,0.05,39.81,PIX,4.0,Fevereiro

In [ ]:
#ano

df['ano'] = df['data_venda'].dt.year

df.head()

,id_venda,data_venda,id_cliente,nome_cliente,cidade,estado,categoria,produto,quantidade,valor_unitario,desconto,valor_total,forma_pagamento,avaliacao_cliente,mes,ano
0,1,2024-02-22,347,Cliente_0347,Porto Alegre,RS,Eletrônicos,Smartphone,2,1754.83,0.00,3509.67,PIX,5.0,Fevereiro,2024
1,2,2024-09-15,309,Cliente_0309,São Paulo,SP,Casa & Decoração,Luminária,2,140.63,0.00,281.26,Cartão de Crédito,2.0,Setembro,2024
2,3,2024-01-04,389,Cliente_0389,Olinda,PE,Casa & Decoração,Tapete,3,312.87,0.20,750.90,PIX,5.0,Janeiro,2024
3,4,2024-02-17,195,Cliente_0195,Belo Horizonte,MG,Alimentos,Azeite Importado,3,80.56,0.00,241.68,Boleto,3.0,Fevereiro,2024
4,5,2024-02-10,283,Cliente_0283,Olinda,PE,Alimentos,Café Premium,1,41.90,0.05,39.81,PIX,4.0,Fevereiro,2024

In [ ]:
#trimestre

df['trimestre'] = df['data_venda'].dt.quarter

df.head()

,id_venda,data_venda,id_cliente,nome_cliente,cidade,estado,categoria,produto,quantidade,valor_unitario,desconto,valor_total,forma_pagamento,avaliacao_cliente,mes,ano,trimestre
0,1,2024-02-22,347,Cliente_0347,Porto Alegre,RS,Eletrônicos,Smartphone,2,1754.83,0.00,3509.67,PIX,5.0,Fevereiro,2024,1
1,2,2024-09-15,309,Cliente_0309,São Paulo,SP,Casa & Decoração,Luminária,2,140.63,0.00,281.26,Cartão de Crédito,2.0,Setembro,2024,3
2,3,2024-01-04,389,Cliente_0389,Olinda,PE,Casa & Decoração,Tapete,3,312.87,0.20,750.90,PIX,5.0,Janeiro,2024,1
3,4,2024-02-17,195,Cliente_0195,Belo Horizonte,MG,Alimentos,Azeite Importado,3,80.56,0.00,241.68,Boleto,3.0,Fevereiro,2024,1
4,5,2024-02-10,283,Cliente_0283,Olinda,PE,Alimentos,Café Premium,1,41.90,0.05,39.81,PIX,4.0,Fevereiro,2024,1

In [ ]:
#Verificar e remover duplicatas, se existirem

df.duplicated().sum()

np.int64(0)

In [ ]:
#Padronizar textos, descobrir quais colunas são de texto.

colunas_texto = df.select_dtypes(include='object').columns

print('Colunas de Texto:', colunas_texto)

Colunas de Texto: Index(['nome_cliente', 'cidade', 'estado', 'categoria', 'produto',
       'forma_pagamento', 'mes'],
      dtype='str')

D:\Users\Aluno\AppData\Local\Temp\ipykernel_18980\60743550.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  colunas_texto = df.select_dtypes(include='object').columns

In [ ]:
##Padronizar textos (ex: remover espaços, corrigir capitalização com .str.strip() e .str.title())

for coluna in colunas_texto:
    df[coluna] = df[coluna].str.strip().str.title()

In [ ]:
#Validar se valor_total está coerente com quantidade * valor_unitario * (1 - desconto)

df['valor_total'] = (df['quantidade'] * df['valor_unitario'] * (1 - df['desconto'])).round(2)

df.head()

,id_venda,data_venda,id_cliente,nome_cliente,cidade,estado,categoria,produto,quantidade,valor_unitario,desconto,valor_total,forma_pagamento,avaliacao_cliente,mes,ano,trimestre
0,1,2024-02-22,347,Cliente_0347,Porto Alegre,Rs,Eletrônicos,Smartphone,2,1754.83,0.00,3509.66,Pix,5.0,Fevereiro,2024,1
1,2,2024-09-15,309,Cliente_0309,São Paulo,Sp,Casa & Decoração,Luminária,2,140.63,0.00,281.26,Cartão De Crédito,2.0,Setembro,2024,3
2,3,2024-01-04,389,Cliente_0389,Olinda,Pe,Casa & Decoração,Tapete,3,312.87,0.20,750.89,Pix,5.0,Janeiro,2024,1
3,4,2024-02-17,195,Cliente_0195,Belo Horizonte,Mg,Alimentos,Azeite Importado,3,80.56,0.00,241.68,Boleto,3.0,Fevereiro,2024,1
4,5,2024-02-10,283,Cliente_0283,Olinda,Pe,Alimentos,Café Premium,1,41.90,0.05,39.80,Pix,4.0,Fevereiro,2024,1

## Etapa 3 — Análise Exploratória de Dados — EDA (Python / Pandas / NumPy)

In [ ]:
## Análise Geral
#1 Qual foi o faturamento total no período analisado?

faturamento_total = df['valor_total'].sum()

print(f'Faturamento Total: {faturamento_total:,.2f}')

Faturamento Total: 2,730,022.47

In [ ]:
#Qual foi o ticket médio por venda?

ticket_medio = df['valor_total'].mean()

print(f'Ticket Médio por Venda: {ticket_medio:,.2f}')

Ticket Médio por Venda: 1,365.01

In [ ]:
#Quantas vendas foram realizadas no total?

total_vendas = df.shape[0]

print(f'Total de Vendas: {total_vendas}')

Total de Vendas: 2000

In [ ]:
## Análise Temporal

#4Como o faturamento evoluiu mês a mês? Houve sazonalidade?

faturamento_mensal = df.groupby(['ano', 'mes'])['valor_total'].sum().reset_index()

faturamento_mensal

     ano        mes  valor_total
0   2024      Abril    151901.74
1   2024     Agosto    218881.82
2   2024   Dezembro    211684.88
3   2024  Fevereiro    258082.14
4   2024    Janeiro    229972.68
5   2024      Julho    194501.55
6   2024      Junho    231492.96
7   2024       Maio    226214.34
8   2024      Março    286268.51
9   2024   Novembro    238534.71
10  2024    Outubro    222654.27
11  2024   Setembro    259832.87

In [ ]:
#5 Qual foi o mês com maior e menor volume de vendas?

vendas_mensais = df.groupby(['ano', 'mes'])['quantidade'].sum().reset_index()

mes_maior_vendas = vendas_mensais.loc[vendas_mensais['quantidade'].idxmax()]
mes_menor_vendas = vendas_mensais.loc[vendas_mensais['quantidade'].idxmin()]

print(f'Mês com maior volume de vendas: {mes_maior_vendas["mes"]} ({mes_maior_vendas["quantidade"]})')

print(f'Mês com menor volume de vendas: {mes_menor_vendas["mes"]} ({mes_menor_vendas["quantidade"]})')

Mês com maior volume de vendas: Novembro (577)
Mês com menor volume de vendas: Abril (404)

In [ ]:
##Análise por Categoria e Produto
#6 Qual categoria gerou maior receita?

receita_categoria = df.groupby('categoria')['valor_total'].sum().reset_index()
categoria_maior_receita = receita_categoria.loc[receita_categoria['valor_total'].idxmax()]

print(f'Categoria com maior receita: {categoria_maior_receita["categoria"]} ({categoria_maior_receita["valor_total"]:,.2f})')

Categoria com maior receita: Eletrônicos (2,163,337.59)

In [ ]:
#7 Quais são os 5 produtos mais vendidos em quantidade?

produtos_mais_vendidos = df.groupby('produto')['quantidade'].sum().reset_index().sort_values(by='quantidade', ascending=False).head(5)

print('5 Produtos mais vendidos em quantidade:')
print(produtos_mais_vendidos)

5 Produtos mais vendidos em quantidade:
         produto  quantidade
17          Vaso         393
19  Whey Protein         323
0       Almofada         320
10      Notebook         316
12    Smartphone         311

In [ ]:
#8 Qual categoria tem a maior média de avaliação dos clientes?

categoria_maior_media_avaliacao = df.groupby('categoria')['avaliacao_cliente'].mean().reset_index().sort_values(by='avaliacao_cliente', ascending=False).head(1)

print('Categoria com a maior média de avaliação dos clientes:')
print(categoria_maior_media_avaliacao)

Categoria com a maior média de avaliação dos clientes:
   categoria  avaliacao_cliente
3  Vestuário           4.183884

In [ ]:
#Análise Geográfica
# 9 Quais são os 5 estados com maior faturamento?

faturamento_estados = df.groupby('estado')['valor_total'].sum().reset_index().sort_values(by='valor_total', ascending=False).head(5)

faturamento_estados

  estado  valor_total
2     Go    315699.36
9     Sp    306921.61
5     Pr    295209.69
1     Ce    282111.37
0     Ba    279164.48

In [ ]:
#10 Existe relação entre a cidade/estado e a forma de pagamento preferida?

preferencia_pagamento = (
    df.groupby(['estado', 'forma_pagamento'])
    .size()
    .reset_index(name='quantidade_vendas')
    .sort_values(['estado', 'quantidade_vendas'], ascending=[True, False])

)

preferencia_pagamento.head(20)

   estado    forma_pagamento  quantidade_vendas
1      Ba  Cartão De Crédito                 84
3      Ba                Pix                 64
0      Ba             Boleto                 30
2      Ba           Dinheiro                 18
5      Ce  Cartão De Crédito                 98
7      Ce                Pix                 49
4      Ce             Boleto                 26
6      Ce           Dinheiro                 18
9      Go  Cartão De Crédito                 96
11     Go                Pix                 77
8      Go             Boleto                 31
10     Go           Dinheiro                 22
13     Mg  Cartão De Crédito                 91
15     Mg                Pix                 66
12     Mg             Boleto                 33
14     Mg           Dinheiro                 21
17     Pe  Cartão De Crédito                 94
19     Pe                Pix                 51
16     Pe             Boleto                 34
18     Pe           Dinheiro                 22

In [ ]:
## Análise de Clientes
#11 Qual a distribuição das formas de pagamento utilizadas?

df.groupby('forma_pagamento').size()

forma_pagamento
Boleto               295
Cartão De Crédito    914
Dinheiro             184
Pix                  607
dtype: int64

In [ ]:
#12 Qual a média de avaliação geral dos clientes? Como ela varia por categoria?

media_avaliacao_geral = df['avaliacao_cliente'].mean()

print(f'Média geral de avaliação: {media_avaliacao_geral:.2f}')

Média geral de avaliação: 4.08

In [ ]:
# Como ela varia por categoria?

media_categoria_avaliacao = df.groupby('categoria')['avaliacao_cliente'].mean().reset_index().sort_values(by='avaliacao_cliente', ascending=False)

media_categoria_avaliacao

          categoria  avaliacao_cliente
3         Vestuário           4.183884
1  Casa & Decoração           4.093511
0         Alimentos           4.069530
2       Eletrônicos           3.975155

In [ ]:
df.to_csv(
    "vendas_varejo_facil_tratado.csv",
    index=False
)